name: afd_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.01.04=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.20=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - greenlet=3.2.4=py311h885b0b7_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.11=py311haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.9.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=py311haa95532_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libsodium=1.0.20=hc70643c_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=1.26.4=py311h12f7302_1
  - numpy-base=1.26.4=py311he4e2855_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py311haa95532_1
  - pandas=2.1.4=py311hf62ec03_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-dotenv=1.2.1=py311haa95532_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - requests=2.32.5=py311haa95532_1
  - scikit-learn=1.5.1=py311hea22821_0
  - scipy=1.16.3=py311hbd6d557_0
  - setuptools=80.10.1=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlalchemy=2.0.45=py311hda9a48d_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - threadpoolctl=3.5.0=py311h4442805_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
prefix: C:\Users\maria\.conda\envs\afd_project
